services:
  ib-gateway:
    restart: always
    build:
      context: ./stable
    image: ghcr.io/gnzsnz/ib-gateway:stable
    env_file:
      - ./.env
    environment:
      TZ: ${TIME_ZONE:-Etc/UTC}
      CUSTOM_CONFIG: ${CUSTOM_CONFIG:-NO}
    secrets:
      - tws_password_paper
      - vnc_password
      - tws_password
    volumes:
      - default_volume:/home/ibgateway/data:ro
#      - ${PWD}/jts.ini:/home/ibgateway/Jts/jts.ini
#      - ${PWD}/config.ini:/home/ibgateway/ibc/config.ini
#      - ${PWD}/tws_settings/:${TWS_SETTINGS_PATH:-/home/ibgateway/Jts}
#      - ${PWD}/ssh/:/home/ibgateway/.ssh
    ports:
      - "127.0.0.1:4001:4003"
      - "127.0.0.1:4002:4004"
      - "127.0.0.1:5900:5900"
    networks:
      - ib-network
secrets:
  tws_password_paper:
    file: pass/tws_password_paper.txt
  vnc_password:
    file: pass/vnc_password.txt
  tws_password:
    file: pass/tws_password.txt

networks:
  ib-network:
    driver: bridge

volumes:
  default_volume: